baseurl = "https://www.ponylang.io"
languageCode = "en-us"
title = "Pony"
metadataformat = "TOML"
canonifyurls = false
# Enable Google Analytics by entering your tracking id

[params]
	# General information
	description = "Pony - High Performance Actor Programming"
	copyright = "Pony Developers"

	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/ponylang/ponyc"

	logo = "/images/logo.png"
	favicon = ""

	permalink = "#"

	# Custom assets
	custom_css = ["stylesheets/pony-material.css"]
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "brown"
    	accent  = "deep-orange"

    [params.font]
    	text = "Roboto"
    	code = "Roboto Mono"

[social]
	twitter = "ponylang"
	github  = "ponylang"

[[menu.main]]
	name   = "Pony"
	url    = "/"
	weight = 1

[[menu.main]]
	name   = "New to Pony?"
	url    = "/discover/"
	weight = 10

[[menu.main]]
	name   = "Learning Pony?"
	url    = "/learn/"
	weight = 20

[[menu.main]]
	name   = "Existing User?"
	url    = "/reference/"
	weight = 30

[[menu.main]]
	name   = "Looking to contribute?"
	url    = "/contribute/"
	weight = 40

[[menu.main]]
	name   = "Community"
	url    = "/community/"
	weight = 50

[[menu.main]]
	name   = "Blog"
	url    = "/blog/"
	weight = 60

[[menu.main]]
	name   = "FAQ"
	url    = "/faq/"
	weight = 70

[[menu.main]]
	name   = "Code of Conduct"
	url    = "/community/code-of-conduct/"
	weight = 80

[[menu.main]]
	name   = "Sponsors"
	url    = "/sponsors/"
	weight = 90

[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true

[permalinks]
  blog = "/blog/:year/:month/:slug/"

[taxonomies]
  category = "categories"
  tag = "tags"
