[Settings]
# Added automatically by the Netlify CLI. It has no effect during normal
# Git-backed deploys.
ID = "Your_Site_ID"

# Settings in the [build] context are global and are applied to all contexts
# unless otherwise overridden by more specific contexts.
[build]
  base = ""
  publish = "public/"
  command = "hugo"

# Have to set HUGO_VERSION for each environment otherwise we get the 0.17 default
[context.production.environment]
  HUGO_VERSION = "0.24.1"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.24.1"

[context.branch-deploy.environment]
  HUGO_VERSION = "0.24.1"

[[redirects]]
  from = "/categories/*"
  to = "/blog/categories/:splat"
  status = 301
  force = true
