name: PR

on: pull_request

concurrency:
  group: pr-${{ github.ref }}
  cancel-in-progress: true

permissions:
  packages: read

jobs:
  superlinter:
    name: Lint markdown
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4.1.1
      - name: Lint codebase
        uses: docker://github/super-linter:v3.8.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_MD: true
          DEFAULT_BRANCH: main

  check-spelling:
    name: Spellcheck markdown
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4.1.1
      - name: Find changed files
        # version v46.0.5
        uses: tj-actions/changed-files@ed68ef82c095e0d48ec87eccea555d944a631a4c
        id: find-changed-files
      - name: Check spelling
        # version 0.51.0
        uses: rojopolis/spellcheck-github-actions@35a02bae020e6999c5c37fabaf447f2eb8822ca7
        with:
          task_name: Changed
          source_files: ${{ steps.find-changed-files.outputs.all_changed_files }}
