name: PR

on: pull_request

concurrency:
  group: pr-${{ github.ref }}
  cancel-in-progress: true

jobs:
  superlinter:
    name: Lint markdown
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4.1.1
      - name: Lint codebase
        uses: docker://github/super-linter:v3.8.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_MD: true
          DEFAULT_BRANCH: main

  check-spelling:
    name: Spellcheck markdown
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4.1.1
      - name: Check spelling
        uses: rojopolis/spellcheck-github-actions@e0dcc87bedf34ff10d6be443753f1c770bacbaa2

  validate-site:
    name: mkdocs build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4.1.1
      - name: Install dependencies
        run: pip install -r requirements.txt
        env:
          INSIDERS_PAT: ${{ secrets.MATERIAL_INSIDERS_ACCESS }}
      - name: Build site
        run: mkdocs build
        env:
          # turn off external url checking as it takes a long time and we
          # do that on a schedule
          VALIDATE_EXTERNAL_URLS: false
