name: Verify site builds

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'

permissions:
  packages: read

jobs:
  test:
    name: Verify site builds
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4.1.1
      - name: Install dependencies
        run: pip install -r requirements.txt
        env:
          INSIDERS_PAT: ${{ secrets.MATERIAL_INSIDERS_ACCESS }}
      - name: Build site
        run: mkdocs build
      - name: Send alert on failure
        if: ${{ failure() }}
        uses: zulip/github-actions-zulip/send-message@e4c8f27c732ba9bd98ac6be0583096dea82feea5
        with:
          api-key: ${{ secrets.ZULIP_SCHEDULED_JOB_FAILURE_API_KEY }}
          email: ${{ secrets.ZULIP_SCHEDULED_JOB_FAILURE_EMAIL }}
          organization-url: 'https://ponylang.zulipchat.com/'
          to: notifications
          type: stream
          topic: ${{ github.repository }} scheduled job failure
          content: ${{ github.server_url}}/${{ github.repository }}/actions/runs/${{ github.run_id }} failed.
